AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Handler: handler
    Runtime: go1.x
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          LambdaAuth:
            AuthorizerPayloadFormatVersion: 2.0
            FunctionArn: !GetAtt Auth.Arn
            EnableSimpleResponses: true    
            Identity:
              Headers:
                - Cookie
  Auth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Policies:
        DynamoDBCrudPolicy:
          TableName: Fitbit

  UserManagement:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_management/
      Policies:
        DynamoDBCrudPolicy:
          TableName: Fitbit
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
            ApiId: !Ref ApiGatewayApi
        SignUp:
          Type: HttpApi
          Properties:
            Path: /signup
            ApiId: !Ref ApiGatewayApi 
            Method: post
        RenderSignup:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGatewayApi 
            Path: /signup
            Method: get
        RenderLogin:
          Type: HttpApi
          Properties:
            Path: /login
            ApiId: !Ref ApiGatewayApi 
            Method: Get
        Login:
          Type: HttpApi
          Properties:
            Path: /login
            ApiId: !Ref ApiGatewayApi 
            Method: Post


  ProfileManagement:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: profile/
      Policies:
        DynamoDBCrudPolicy:
          TableName: Fitbit
      Events:
        ReadProfile:
          Type: HttpApi
          Properties:
            Path: /profile
            Method: Get
            ApiId: !Ref ApiGatewayApi 
        UpdateProfile:
          Type: HttpApi
          Properties:
            Path: /profile
            ApiId: !Ref ApiGatewayApi 
            Method: Post


  TermsOfService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: terms/
      Events:
        CatchAll:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /terms
            ApiId: !Ref ApiGatewayApi 
            Method: GET


  Oauth:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: webhook_oauth/
      Policies:
        DynamoDBCrudPolicy:
          TableName: Fitbit
      Events:
        GetCode:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth_code
            ApiId: !Ref ApiGatewayApi 
            Method: GET
        Token:
          Type: HttpApi
          Properties:
            Path: /webhook
            Method: GET
            ApiId: !Ref ApiGatewayApi 

  PrivacyPolicy:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: privacy/
      Events:
        CatchAll:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /privacy
            ApiId: !Ref ApiGatewayApi 
            Method: GET

  WebhookData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: webhook_data/
      Policies:
        DynamoDBCrudPolicy:
          TableName: Fitbit
      Events:
        CatchAll:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook_data
            ApiId: !Ref ApiGatewayApi 
            Method: POST
        GetRequest:
          Type: HttpApi
          Properties:
            Path: /webhook_data
            Method: GET
            ApiId: !Ref ApiGatewayApi 
